### ISSUE TITLE
Hackintosh

### ISSUE THREAD

**Issue by johnnynunez** [zxystd/AppleIntelWifiAdapter#2]
怎样才可以在intel的黑苹果使用WiFi和蓝牙?

**Comment by johnnynunez** [comment]
I have kernel panic on 10.15.2

**Comment by rv32ima** [comment]
re: kernel panic, such happens due to an invalid access in `IO80211Controller::free`. The driver is able to probe, initialize, etc, but the kpanic occurs when the driver is being released.
```c
void __thiscall free(IO80211Controller *this)

{
  if ((long *)this->field_0x3a8 != (long *)0x0) { // crashes here
    (**(code **)(*(long *)this->field_0x3a8 + 0x28))();
    this->field_0x3a8 = 0;
  }
  if ((long *)this->field_0x3c0 != (long *)0x0) {
    (**(code **)(*(long *)this->field_0x3c0 + 0x118))();
    this->field_0x3c0 = 0;
  }
  if (___ZL15_interfaceNamer.llvm.10861393931100522170 != (long *)0x0) {
    (**(code **)(*___ZL15_interfaceNamer.llvm.10861393931100522170 + 0x28))();
  }
  __GLOBAL__sub_I_IO80211AssociationJoinSnapshot.cpp(this->field_0x140);
                    /* WARNING: Could not recover jumptable at 0x00072458. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(PTR__.str.13.llvm.2158329364282267806_000f50f0 + 0xa0))(this);
  return;
}
```

This occurs because the reversed IO80211Controller.h header file has several missing class variables and can be easily fixed by adding ~684 bytes of filler space at the end of the class.

**Comment by alexbarnsley** [comment]
Hi @hatf0, I don't suppose you could elaborate on this at all, please? I tried adding the filler bytes but it doesn't seem to have an effect on anything. I'm not very C++ savvy so I could be being stupid. Thanks!
